version: '3.8'

services:
  bilgeadamproject.webapi:
    image: ${DOCKER_REGISTRY-}bilgeadamprojectwebapi
    build:
      context: .
      dockerfile: BilgeAdamProject.WebApi/Dockerfile
    ports:
    - "51500:8080"
    - "51502:8081"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres




